let items = [{
    'name': 'Adamant Pill',
    'icon': require('./assets/items/unknown_orange.png'),
    'description': 'Temporarily makes your skin as hard as adamant. Potent!',
    'rarity': '4',
    'value': '260',
    'maxCapacity': '5',
}, {
    'name': 'Advanced Armor Sphere',
    'icon': require('./assets/items/sphere_orange.png'),
    'description': 'Reacts uniquely to heat. Fuse this to armor to improve it.',
    'rarity': '6',
    'value': '300',
    'maxCapacity': '99',
}, {
    'name': 'Ancient Potion',
    'icon': require('./assets/items/unknown_orange.png'),
    'description': 'Fully restores health and maximizes the size of your Health and Stamina Gauges.',
    'rarity': '5',
    'value': '345',
    'maxCapacity': '1',
}, {
    'name': 'Antidote',
    'icon': require('./assets/items/potion_blue.png'),
    'description': 'A cure for poison.',
    'rarity': '1',
    'value': '6',
    'maxCapacity': '10',
}, {
    'name': 'Appreciation Fireworks',
    'icon': require('./assets/items/bomb_bright_yellow.png'),
    'description': 'Fireworks you receive for attending the Appreciation Fest. Show your thanks by lighting these fireworks!',
    'rarity': '3',
    'value': '7',
    'maxCapacity': '10',
},{
    'name': 'Armorcharm',
    'icon': require('./assets/items/sac_orange.png'),
    'description': 'An amulet that increases defense. Just carrying this hardens your skin like stone.',
    'rarity': '5',
    'value': '2400',
    'maxCapacity': '1',
}, {
    'name': 'Armor Sphere',
    'icon': require('./assets/items/sphere_blue.png'),
    'description': 'Reacts uniquely to heat. Fuse this to armor to improve it by a tiny amount.',
    'rarity': '4',
    'value': '80',
    'maxCapacity': '99',
}, {
    'name': 'Armor Sphere+',
    'icon': require('./assets/items/sphere_green.png'),
    'description': 'Reacts uniquely to heat. Fuse this to armor to improve it by a small amount.',
    'rarity': '5',
    'value': '200',
    'maxCapacity': '99',
}, {
    'name': 'Arowana Bait',
    'icon': require('./assets/items/fishing_green.png'),
    'description': 'A ball of bait favored by fish of the Arowana family.',
    'rarity': '2',
    'value': '15',
    'maxCapacity': '10',
}, {
    'name': 'Astera Jerky',
    'icon': require('./assets/items/meat_red.png'),
    'description': 'Juicy, dried meat made by Astera\'s chef. Boosts natural healing and cures bleeding.',
    'rarity': '2',
    'value': '10',
    'maxCapacity': '5',
}, {
    'name': 'Autumn Harvest Ticket',
    'icon': require('./assets/items/paper_orange.png'),
    'description': 'A ticket you receive for attending the Autumn Harvest Fest. Can be exchanged for special equipment or fireworks.',
    'rarity': '4',
    'value': '200',
    'maxCapacity': '99',
}, {
    'name': 'Baitbug',
    'icon': require('./assets/items/fishing_red.png'),
    'description': 'An insect used as fishing bait. A fish favorite, it practically races down the nearest gilly gullet.',
    'rarity': '3',
    'value': '2',
    'maxCapacity': '10',
}, {
    'name': 'Barrel Bomb',
    'icon': require('./assets/items/bomb_bright_yellow.png'),
    'description': 'A small time bomb.',
    'rarity': '2',
    'value': '16',
    'maxCapacity': '10',
}, {
    'name': 'Bhernastone',
    'icon': require('./assets/items/ore_light_blue.png'),
    'description': 'An Old World import. Beautiful, but not suitable for crafting. (Trade-in Item)',
    'rarity': '4',
    'value': '400',
    'maxCapacity': '99',
}, {
    'name': 'Binoculars',
    'icon': require('./assets/items/binoculars.png'),
    'description': 'Allows you to see farther and observe from a distance.',
    'rarity': '1',
    'value': '5',
    'maxCapacity': '1',
}, {
    'name': 'Bitterbug',
    'icon': require('./assets/items/bug_blue.png'),
    'description': 'A sharp-tasting bug with innate healing abilities. Used as an ingredient in many medicines.',
    'rarity': '1',
    'value': '2',
    'maxCapacity': '10',
}, {
    'name': 'Blastnut',
    'icon': require('./assets/items/husk_yellow.png'),
    'description': 'A nut used to make sticky ammo',
    'rarity': '1',
    'value': '4',
    'maxCapacity': '30',
}, {
    'name': 'Blast Coating',
    'icon': require('./assets/items/coating_yellow.png'),
    'description': 'An arrow coating that applies explosive powder to arrows. Capacity: 20',
    'rarity': '3',
    'value': '6',
    'maxCapacity': '20',
}, {
    'name': 'Blossom Fireworks',
    'icon': require('./assets/items/bomb_red.png'),
    'description': 'Fireworks you receive for attending the Spring Blossom Fest. Light up the sky and enjoy the festivies!',
    'rarity': '3',
    'value': '7',
    'maxCapacity': '10',
}, {
    'name': 'Blue Mushroom',
    'icon': require('./assets/items/mushroom_blue.png'),
    'description': 'A mushroom infused with power-enhancing effects. Used in restorative items.',
    'rarity': '2',
    'value': '2',
    'maxCapacity': '10',
}, {
    'name': 'Bomberry',
    'icon': require('./assets/items/husk_red.png'),
    'description': 'A nut that ruptures on impact. Used to make cluster bombs.',
    'rarity': '2',
    'value': '12',
    'maxCapacity': '10',
}, {
    'name': 'Boomerang',
    'icon': require('./assets/items/boomerang.png'),
    'description': 'An unusually-shaped weapon from abroad that returns to its user when thrown.',
    'rarity': '4',
    'value': '15',
    'maxCapacity': '5',
}, {
    'name': 'Bounce Bomb',
    'icon': require('./assets/items/bomb_light_blue.png'),
    'description': 'Launches into the air when set. This modified bomb requires skill to use.',
    'rarity': '2',
    'value': '18',
    'maxCapacity': '5',
}, {
    'name': 'Catalyst',
    'icon': require('./assets/items/sac_green.png'),
    'description': 'Works with other materials to enhance their effects. Cannot be used by itself.',
    'rarity': '2',
    'value': '48',
    'maxCapacity': '5',
}, {
    'name': 'Chillshroom',
    'icon': require('./assets/items/mushroom_white.png'),
    'description': 'This mushroom is a primary ingredient in cool drinks.',
    'rarity': '3',
    'value': '18',
    'maxCapacity': '10',
}, {
    'name': 'Cluster Bomb 1',
    'icon': require('./assets/items/ammo_red.png'),
    'description': 'Ammo that fragments into three shells upon impact. Beware of friendly fire! Capacity: 3',
    'rarity': '2',
    'value': '6',
    'maxCapacity': '3',
}, {
    'name': 'Cluster Bomb 2',
    'icon': require('./assets/items/ammo_red.png'),
    'description': 'Ammo that fragments into four shells upon impact. Beware of friendly fire! Capacity: 3',
    'rarity': '3',
    'value': '6',
    'maxCapacity': '3',
}, {
    'name': 'Cool Drink',
    'icon': require('./assets/items/potion_white.png'),
    'description': 'Provides temporary relief from extreme heat.',
    'rarity': '1',
    'value': '30',
    'maxCapacity': '5',
}, {
    'name': 'Dash Extract',
    'icon': require('./assets/items/potion_yellow.png'),
    'description': 'A mysterious substance culled from certain monsters that increases endurance.',
    'rarity': '4',
    'value': '56',
    'maxCapacity': '20',
}, {
    'name': 'Dash Juice',
    'icon': require('./assets/items/potion_yellow.png'),
    'description': 'Dulls one\'s sense of exhaustion. Reduces stamina depletion for a time.',
    'rarity': '2',
    'value': '29',
    'maxCapacity': '5',
}, {
    'name': 'Deluxe First Wyverian Print',
    'icon': require('./assets/items/paper_green.png'),
    'description': 'A ticket with a handprint, used by the First Wyverians. You can exchange it for items at the Melding Pot.',
    'rarity': '4',
    'value': '0',
    'maxCapacity': '99',
}, {
    'name': 'Demon Powder',
    'icon': require('./assets/items/sac_red.png'),
    'description': 'A mysterious powder that produces a cloud around the area that temporarily strengthens attacks.',
    'rarity': '4',
    'value': '315',
    'maxCapacity': '3',
}, {
    'name': 'Devil\'s Blight',
    'icon': require('./assets/items/mushroom_red.png'),
    'description': 'A very rare fungus that pulses with extreme heat. Add to a barrel bomb for a dramatically stronger blast.',
    'rarity': '2',
    'value': '60',
    'maxCapacity': '10',
}, {
    'name': 'Dragoncore Ore',
    'icon': require('./assets/items/round_ore_orange.png'),
    'description': 'A valuable mineral used to create charms. Gives off a mysterious glow that grants the holder sagely wisdom.',
    'rarity': '8',
    'value': '2000',
    'maxCapacity': '99',
}, {
    'name': 'Dragonfell Berry',
    'icon': require('./assets/items/seed_red.png'),
    'description': 'A mysterious berry, rumored for eons to be loathed by dragons. Required to craft Dragon Ammo.',
    'rarity': '4',
    'value': '78',
    'maxCapacity': '10',
}, {
    'name': 'Dragonstrike Nut',
    'icon': require('./assets/items/husk_yellow.png'),
    'description': 'A nut that explodes on impact. Used to make wyvern ammo.',
    'rarity': '2',
    'value': '12',
    'maxCapacity': '5',
}, {
    'name': 'Dundormarin',
    'icon': require('./assets/items/ore_blue.png'),
    'description': 'An Old World import. Beautiful, but not suitable for crafting. (Trade-in Item)',
    'rarity': '4',
    'value': '800',
    'maxCapacity': '99',
}, {
    'name': 'Dung',
    'icon': require('./assets/items/dung_orange.png'),
    'description': 'Exudes a prodigious smell. Used to make ammo for your slinger called dung pods.',
    'rarity': '1',
    'value': '1',
    'maxCapacity': '10',
}, {
    'name': 'Dung Pod',
    'icon': require('./assets/items/unknown_orange.png'),
    'description': 'Slinger ammo that releases a strong odor on impact. Causes certain monsters to flee.',
    'rarity': '2',
    'value': '20',
    'maxCapacity': '10',
}, {
    'name': 'Empty Phial',
    'icon': require('./assets/items/empty_phial.png'),
    'description': 'A regular old empty phial. Nothing more, nothing less.',
    'rarity': '1',
    'value': '1',
    'maxCapacity': '99',
}, {
    'name': 'Energy Drink',
    'icon': require('./assets/items/potion_bright_yellow.png'),
    'description': 'A Guild-approved beverage that boosts your stamina. Helps shake off sleep, too!',
    'rarity': '2',
    'value': '6',
    'maxCapacity': '10',
}, {
    'name': 'Exciteshroom',
    'icon': require('./assets/items/mushroom_green.png'),
    'description': 'This one has a very strange aroma. Is it edible? Only one way to find out! Required to craft Farcasters.',
    'rarity': '3',
    'value': '18',
    'maxCapacity': '10',
}, {
    'name': 'Exhaust Ammo 1',
    'icon': require('./assets/items/ammo_blue.png'),
    'description': 'Ammo that drains a monster\'s stamina. Capacity: 12',
    'rarity': '2',
    'value': '3',
    'maxCapacity': '12',
}, {
    'name': 'Exhaust Ammo 2',
    'icon': require('./assets/items/ammo_blue.png'),
    'description': 'Enhanced ammo that drains a monster\'s stamina. Capacity: 8',
    'rarity': '3',
    'value': '5',
    'maxCapacity': '8',
}, {
    'name': 'Fire Dragon Scale+',
    'icon': require('./assets/items/scale_red.png'),
    'description': 'Rare Teostra material. Mostly obtained by carving. Broadly used for many purposes.',
    'rarity': '7',
    'value': '2300',
    'maxCapacity': '99',
}, {
    'name': 'Fire Herb',
    'icon': require('./assets/items/herb_orange.png'),
    'description': 'A wondrous, flammable plant. Useful for crafting explosives.',
    'rarity': '2',
    'value': '4',
    'maxCapacity': '20',
}, {
    'name': 'Firecell Stone',
    'icon': require('./assets/items/ore_orange.png'),
    'description': 'A magma-like deposit that only trained hands can work with. Armor made from it is first-class.',
    'rarity': '7',
    'value': '1720',
    'maxCapacity': '99',
}, {
    'name': 'First Wyverian Print',
    'icon': require('./assets/items/paper_green.png'),
    'description': 'A ticket with a handprint, used by the First Wyverians. You can exchange it for items at the Melding Pot.',
    'rarity': '4',
    'value': '0',
    'maxCapacity': '99',
}, {
    'name': 'Flamenut',
    'icon': require('./assets/items/seed_white.png'),
    'description': 'Used to make gunpowder that increases ammo firepower.',
    'rarity': '2',
    'value': '12',
    'maxCapacity': '80',
}, {
    'name': 'Flame Sac',
    'icon': require('./assets/items/sac_red.png'),
    'description': 'A monster organ filled with flamamble powder. Handle with extreme care.',
    'rarity': '4',
    'value': '800',
    'maxCapacity': '99',
}, {
    'name': 'Flaming Ammo',
    'icon': require('./assets/items/ammo_orange.png'),
    'description': 'Ammo that packs a punch against monsters suspectible to fire. Capacity: 60',
    'rarity': '2',
    'value': '2',
    'maxCapacity': '60',
}, {
    'name': 'Flashbug',
    'icon': require('./assets/items/bug_yellow.png'),
    'description': 'An insect that emits a powerful flash when it dies. Required to craft Flash Pods.',
    'rarity': '2',
    'value': '48',
    'maxCapacity': '10',
}, {
    'name': 'Flash Pod',
    'icon': require('./assets/items/unknown_yellow.png'),
    'description': 'Slinger ammo that flashes brightly on impact. Fire it right under a monster\'s nose to blind it.',
    'rarity': '2',
    'value': '57',
    'maxCapacity': '3',
}, {
    'name': 'Flowfern',
    'icon': require('./assets/items/herb_blue.png'),
    'description': 'This plant\'s leaves store a great amount of water. A component for making Water Ammo.',
    'rarity': '1',
    'value': '4',
    'maxCapacity': '20',
}, {
    'name': 'Freeze Ammo',
    'icon': require('./assets/items/ammo_white.png'),
    'description': 'Ammo that packs a punch against monsters susceptible to ice. Capacity: 60',
    'rarity': '2',
    'value': '2',
    'maxCapacity': '60',
}, {
    'name': 'Freezer Sac',
    'icon': require('./assets/items/sac_white.png'),
    'description': 'A monster organ with tremendous freezing power. Turns its surroundings to ice.',
    'rarity': '6',
    'value': '2400',
    'maxCapacity': '99',
}, {
    'name': 'Frost Sac',
    'icon': require('./assets/items/sac_white.png'),
    'description': 'A monster internal organ, filled with extremely low temperature fluid. Handle with care.',
    'rarity': '4',
    'value': '1000',
    'maxCapacity': '99',
}, {
    'name': 'Fucium Ore',
    'icon': require('./assets/items/ore_red.png'),
    'description': 'Ore obtained from the Elder\'s Recess. A mysterious metal, capable of fusing nearly any two materials together.',
    'rarity': '6',
    'value': '1020',
    'maxCapacity': '99',
}, {
    'name': 'Gajalaka Sketch',
    'icon': require('./assets/items/paper_yellow.png'),
    'description': 'Proof of friendship with the Gajalaka tribes of the new continent. Show it to the Smithy and see what happens!',
    'rarity': '4',
    'value': '200',
    'maxCapacity': '99',
}, {
    'name': 'Gleaming Streamstone',
    'icon': require('./assets/items/unknown_purple.png'),
    'description': 'A rare stone taken form a tempered monster. Proof that it ruled for an age as a tyrant unchallenged.',
    'rarity': '8',
    'value': '3000',
    'maxCapacity': '99',
}, {
    'name': 'Godbug',
    'icon': require('./assets/items/bug_white.png'),
    'description': 'An insect said to live a millennium. Combine it with other items to add their properties to the powder.',
    'rarity': '4',
    'value': '120',
    'maxCapacity': '10',
}, {
    'name': 'Gold Wyverian Print',
    'icon': require('./assets/items/paper_yellow.png'),
    'description': 'A ticket with a handprint, used by the First Wyverians. Exchange it for very rare materials at the Melding Pot.',
    'rarity': '4',
    'value': '0',
    'maxCapacity': '99',
}, {
    'name': 'Golden Egg',
    'icon': require('./assets/items/egg_yellow.png'),
    'description': 'An egg of glittering gold. Super valuable and rare, but of no use to a hunter. (Trade-in Item)',
    'rarity': '4',
    'value': '20000',
    'maxCapacity': '99',
}, {
    'name': 'Goldenfish Bait',
    'icon': require('./assets/items/fishing_bright_yellow.png'),
    'description': 'A ball of bait favored by fish of the Goldenfish family.',
    'rarity': '2',
    'value': '30',
    'maxCapacity': '10',
}, {
    'name': 'Gunpowder',
    'icon': require('./assets/items/sac_orange.png'),
    'description': 'A dangerous substance that explodes when struck or heated.',
    'rarity': '2',
    'value': '45',
    'maxCapacity': '20',
}, {
    'name': 'Gunpowder Level 2',
    'icon': require('./assets/items/sac_white.png'),
    'description': 'Combustible powder. Combine with level 1 ammo to raise its level.',
    'rarity': '2',
    'value': '1',
    'maxCapacity': '80',
}, {
    'name': 'Gunpowder Level 3',
    'icon': require('./assets/items/sac_white.png'),
    'description': 'Highly combustible powder. Combine with level 1 ammo to raise its level.',
    'rarity': '2',
    'value': '3',
    'maxCapacity': '80',
}, {
    'name': 'Gunpowderfish Bait',
    'icon': require('./assets/items/fishing_white.png'),
    'description': 'A ball of bait favored by fish of the Gunpowderfish family.',
    'rarity': '2',
    'value': '15',
    'maxCapacity': '10',
}, {
    'name': 'Hard Armor Sphere',
    'icon': require('./assets/items/sphere_purple.png'),
    'description': 'Reacts uniquely to heat. Fuse this to armor to significantly improve it.',
    'rarity': '7',
    'value': '400',
    'maxCapacity': '99',
}, {
    'name': 'Hardshell Powder',
    'icon': require('./assets/items/sac_yellow.png'),
    'description': 'A mysterious powder that produces a cloud around the area that temporarily strengthens defense.',
    'rarity': '4',
    'value': '315',
    'maxCapacity': '3',
}, {
    'name': 'Harvest Fireworks',
    'icon': require('./assets/items/barrel_orange.png'),
    'description': 'Fireworks you receive for attending the Autumn Harvest Fest. Dance till the ground lights up in a blaze!',
    'rarity': '3',
    'value': '7',
    'maxCapacity': '10',
},{
    'name': 'Heavy Armor Sphere',
    'icon': require('./assets/items/sphere_red.png'),
    'description': 'Reacts uniquely to heat. Fuse this to armor to greatly improve it.',
    'rarity': '8',
    'value': '600',
    'maxCapacity': '99',
}, {
    'name': 'Herb',
    'icon': require('./assets/items/herb_green.png'),
    'description': 'A primary ingredient in potions.',
    'rarity': '1',
    'value': '2',
    'maxCapacity': '10',
}, {
    'name': 'Herbal Medicine',
    'icon': require('./assets/items/unknown_blue.png'),
    'description': 'Removes all traces of poison and restores a slight amount of health.',
    'rarity': '2',
    'value': '25',
    'maxCapacity': '5',
}, {
    'name': 'Herbal Powder',
    'icon': require('./assets/items/sac_blue.png'),
    'description': 'A mysterious powder that produces a cloud around the area that restores health and neutralizes poison.',
    'rarity': '4',
    'value': '315',
    'maxCapacity': '3',
}, {
    'name': 'Hero\'s Streamstone: Blade',
    'icon': require('./assets/monster_materials/hero-streamstone.jpg'),
    'description': 'A material used by legendary heroes. Used to bring out the hidden power in swords and shields and dual blades.',
    'rarity': '8',
    'value': '20000',
    'maxCapacity': '10',
}, {
    'name': 'Hero\'s Streamstone: Hammer',
    'icon': require('./assets/monster_materials/hero-streamstone.jpg'),
    'description': 'A material used by legendary heroes. Used to bring out the hidden power in hammers and hunting horns.',
    'rarity': '8',
    'value': '20000',
    'maxCapacity': '10',
}, {
    'name': 'Hunter Runestone',
    'icon': require('./assets/items/hunter-runestone.png'),
    'description': 'To the Hunter of Astera. An otherwordly stone gifted by Geralt. Depicts a magic sign for controlling fire.',
    'rarity': '4',
    'value': '0',
    'maxCapacity': '1',
},{
    'name': 'Ivy',
    'icon': require('./assets/items/herb_green.png'),
    'description': 'A lightweight and extremely strong plant. Used to make nets for pitfall traps.',
    'rarity': '1',
    'value': '8',
    'maxCapacity': '10',
}, {
    'name': 'Large Barrel',
    'icon': require('./assets/items/barrel_orange.png'),
    'description': 'A large, empty barrel. Combine with gunpowder to make it into a bomb.',
    'rarity': '2',
    'value': '21',
    'maxCapacity': '5',
}, {
    'name': 'Large Barrel Bomb',
    'icon': require('./assets/items/bomb_orange.png'),
    'description': 'A powerful bomb triggered by external physical impact.',
    'rarity': '3',
    'value': '52',
    'maxCapacity': '2',
}, {
    'name': 'Latchberry',
    'icon': require('./assets/items/husk_blue.png'),
    'description': 'A nut that bears a spiral groove. Used to make pierce ammo.',
    'rarity': '1',
    'value': '4',
    'maxCapacity': '99',
}, {
    'name': 'Lifepowder',
    'icon': require('./assets/items/sac_yellow.png'),
    'description': 'Produces a healing cloud in the area around the user.',
    'rarity': '4',
    'value': '315',
    'maxCapacity': '3',
}, {
    'name': 'Loc Lac Ore',
    'icon': require('./assets/items/ore_yellow.png'),
    'description': 'An Old World import. Beautiful, but not suitable for crafting.',
    'rarity': '5',
    'value': '1500',
    'maxCapacity': '99',
}, {
    'name': 'Mandragora',
    'icon': require('./assets/items/mushroom_yellow.png'),
    'description': 'A dangerous fungus said to draw the life out of people. Beware. Required to craft Max Potions.',
    'rarity': '3',
    'value': '40',
    'maxCapacity': '10',
}, {
    'name': 'Max Potion',
    'icon': require('./assets/items/unknown_yellow.png'),
    'description': 'Fully restores health and maximizes the size of your Health Gauge.',
    'rarity': '3',
    'value': '210',
    'maxCapacity': '2',
}, {
    'name': 'Mega Barrel Bomb',
    'icon': require('./assets/items/bomb_orange.png'),
    'description': 'An upgraded large barrel bomb. Effective against large monsters.',
    'rarity': '4',
    'value': '80',
    'maxCapacity': '2',
}, {
    'name': 'Mega Bounce Bomb',
    'icon': require('./assets/items/bomb_light_blue.png'),
    'description': 'An improved version of the bounce bomb. Requires some skill to use.',
    'rarity': '4',
    'value': '68',
    'maxCapacity': '5',
}, {
    'name': 'Mega Man Ticket',
    'icon': require('./assets/items/paper_blue.png'),
    'description': 'A ticket for a special Mega Man tie-in. Gives you access to special 8-bit retro Palico equipment.',
    'rarity': '6',
    'value': '400',
    'maxCapacity': '99',
}, {
    'name': 'Mega Potion',
    'icon': require('./assets/items/potion_green.png'),
    'description': 'Restores a moderate amount of health.',
    'rarity': '2',
    'value': '16',
    'maxCapacity': '10',
}, {
    'name': 'Might Pill',
    'icon': require('./assets/items/unknown_red.png'),
    'description': 'Temporarily endows you with the strength of a mighty god. Potent!',
    'rarity': '4',
    'value': '280',
    'maxCapacity': '5',
}, {
    'name': 'Might Seed',
    'icon': require('./assets/items/seed_red.png'),
    'description': 'Temporarily strengthens your attacks when ingested by improving energy flow.',
    'rarity': '2',
    'value': '140',
    'maxCapacity': '10',
}, {
    'name': 'Minegardenite',
    'icon': require('./assets/items/ore_yellow.png'),
    'description': 'An Old World import. Beautiful, butnot suitable for crafting. (Trade-in Item)',
    'rarity': '7',
    'value': '5000',
    'maxCapacity': '99',
}, {
    'name': 'Needleberry',
    'icon': require('./assets/items/husk_green.png'),
    'description': 'A nut covered in needle-like spines. Used to make spread ammo.',
    'rarity': '1',
    'value': '1',
    'maxCapacity': '99',
}, {
    'name': 'Nitroshroom',
    'icon': require('./assets/items/mushroom_red.png'),
    'description': 'A hard-to-find mushroom with the power to generate blazing heat. Required to craft Gunpowder.',
    'rarity': '2',
    'value': '6',
    'maxCapacity': '20',
}, {
    'name': 'Normal Ammo 2',
    'icon': require('./assets/items/ammo_white.png'),
    'description': 'Non-specialized ammo. More powerful than Normal Ammo 1. Capacity 99',
    'rarity': '2',
    'value': '1',
    'maxCapacity': '99',
}, {
    'name': 'Nulberry',
    'icon': require('./assets/items/seed_blue.png'),
    'description': 'A mysterious berry that cures various blights.',
    'rarity': '2',
    'value': '120',
    'maxCapacity': '10',
}, {
    'name': 'Paralysis Ammo 1',
    'icon': require('./assets/items/ammo_bright_yellow.png'),
    'description': 'Ammo that causes paralysis. Some targets require multiple shots. Capacity: 12',
    'rarity': '2',
    'value': '3',
    'maxCapacity': '12',
}, {
    'name': 'Paralysis Ammo 2',
    'icon': require('./assets/items/ammo_bright_yellow.png'),
    'description': 'Enhanced ammo that causes paralysis. Some targets require multiple shots. Capacity: 8',
    'rarity': '3',
    'value': '5',
    'maxCapacity': '8',
}, {
    'name': 'Paralysis Coating',
    'icon': require('./assets/items/coating_bright_yellow.png'),
    'description': 'An arrow coating that applies paralysis effects to arrows. Capacity: 20',
    'rarity': '3',
    'value': '3',
    'maxCapacity': '20',
}, {
    'name': 'Parashroom',
    'icon': require('./assets/items/mushroom_yellow.png'),
    'description': 'A mushroom that induces paralysis. Required to craft Tranq Bombs.',
    'rarity': '3',
    'value': '15',
    'maxCapacity': '10',
}, {
    'name': 'Pierce Ammo 1',
    'icon': require('./assets/items/ammo_blue.png'),
    'description': 'Armor-piercing ammo that deals multiple hits to some monsters. Capacity: 60',
    'rarity': '1',
    'value': '2',
    'maxCapacity': '60',
}, {
    'name': 'Pierce Ammo 2',
    'icon': require('./assets/items/ammo_blue.png'),
    'description': 'High-grade armor-piercing ammo. Deals more hits than Pierce Ammo 1. Capacity: 60',
    'rarity': '2',
    'value': '2',
    'maxCapacity': '60',
}, {
    'name': 'Pitfall Trap',
    'icon': require('./assets/items/trap_green.png'),
    'description': 'A trap for catching certain large monsters. It is tripped by a heavy weight.',
    'rarity': '3',
    'value': '200',
    'maxCapacity': '1',
}, {
    'name': 'Poison Ammo 1',
    'icon': require('./assets/items/ammo_purple.png'),
    'description': 'Poisons target, but may require several shots. Capacity: 12',
    'rarity': '2',
    'value': '2',
    'maxCapacity': '12',
}, {
    'name': 'Poison Ammo 2',
    'icon': require('./assets/items/ammo_purple.png'),
    'description': 'Enhanced ammo that inflicts poison. Some targets require multiple shots. Capacity: 12',
    'rarity': '3',
    'value': '2',
    'maxCapacity': '12',
}, {
    'name': 'Poison Coating',
    'icon': require('./assets/items/coating_purple.png'),
    'description': 'An arrow coating that applies poison effects to arrows. Capacity: 20',
    'rarity': '3',
    'value': '2',
    'maxCapacity': '20',
}, {
    'name': 'Potion',
    'icon': require('./assets/items/potion_green.png'),
    'description': 'Restores a small amount of health.',
    'rarity': '1',
    'value': '8',
    'maxCapacity': '10',
}, {
    'name': 'Powercharm',
    'icon': require('./assets/items/sac_red.png'),
    'description': 'An amulet that strengthens attacks. Just carrying this gives you demonic strength.',
    'rarity': '5',
    'value': '3600',
    'maxCapacity': '1',
}, {
    'name': 'Power Coating',
    'icon': require('./assets/items/coating_red.png'),
    'description': 'An arrow coating that increases the attack power of arrows. Capacity: 50',
    'rarity': '2',
    'value': '2',
    'maxCapacity': '50',
}, {
    'name': 'Ration',
    'icon': require('./assets/items/meat_yellow.png'),
    'description': 'Food that restores a bit of stamina.',
    'rarity': '1',
    'value': '3',
    'maxCapacity': '10',
}, {
    'name': 'Raw Meat',
    'icon': require('./assets/items/meat_red.png'),
    'description': 'Meat carved from a monster. Can be cooked, combined, or used to set a trap.',
    'rarity': '1',
    'value': '5',
    'maxCapacity': '10',
}, {
    'name': 'Recover Ammo 1',
    'icon': require('./assets/items/ammo_green.png'),
    'description': 'Ammo that restores a small amount of health to an ally upon impact. Capacity: 12',
    'rarity': '2',
    'value': '2',
    'maxCapacity': '12',
}, {
    'name': 'Screamer Pod',
    'icon': require('./assets/items/unknown_white.png'),
    'description': 'Used as ammo for your slinger. Emits a harsh, high-frequency sound that can disrupt sensitive monsters.',
    'rarity': '2',
    'value': '45',
    'maxCapacity': '3',
}, {
    'name': 'Screamer Sac',
    'icon': require('./assets/items/sac_white.png'),
    'description': 'A monster organ that emits an earsplitting sonic blast when ruptured. Used to craft screamer pods.',
    'rarity': '2',
    'value': '15',
    'maxCapacity': '10',
}, {
    'name': 'SFV Ticket',
    'icon': require('./assets/items/paper_white.png'),
    'description': 'A ticket for a special Street Fighter tie-in. Wait...does that mean that legendary fighter is going to...!?',
    'rarity': '4',
    'value': '200',
    'maxCapacity': '99',
}, {
    'name': 'Shock Trap',
    'icon': require('./assets/items/trap_bright_yellow.png'),
    'description': 'A trap that immobilizes a target. Use it to capture monsters.',
    'rarity': '3',
    'value': '160',
    'maxCapacity': '1',
}, {
    'name': 'Silver Egg',
    'icon': require('./assets/items/egg_white.png'),
    'description': 'An egg of glittering silver. Valuable and rare, but of no use to a hunter. (Trade-in Item)',
    'rarity': '4',
    'value': '10000',
    'maxCapacity': '99',
}, {
    'name': 'Silver Wyverian Print',
    'icon': require('./assets/items/paper_white.png'),
    'description': 'A ticket with a handprint, used by the First Wyverians. Exchange it for rare materials at the Melding Pot.',
    'rarity': '4',
    'value': '0',
    'maxCapacity': '99',
}, {
    'name': 'Slashberry',
    'icon': require('./assets/items/husk_white.png'),
    'description': 'Used to make slicing ammo.',
    'rarity': '1',
    'value': '4',
    'maxCapacity': '30',
}, {
    'name': 'Sleep Ammo 1',
    'icon': require('./assets/items/ammo_light_blue.png'),
    'description': 'Ammo that induces sleep. Some targets require multiple shots. Capacity: 12',
    'rarity': '2',
    'value': '2',
    'maxCapacity': '12',
}, {
    'name': 'Sleep Ammo 2',
    'icon': require('./assets/items/ammo_light_blue.png'),
    'description': 'Enhanced ammo that induces sleep. Some targets require multiple shots. Capacity: 8',
    'rarity': '3',
    'value': '3',
    'maxCapacity': '8',
}, {
    'name': 'Sleep Coating',
    'icon': require('./assets/items/coating_light_blue.png'),
    'description': 'An arrow coating that induces sleep. Capacity: 20',
    'rarity': '3',
    'value': '2',
    'maxCapacity': '20',
}, {
    'name': 'Sleep Herb',
    'icon': require('./assets/items/herb_light_blue.png'),
    'description': 'A plant containing sleeping agents. Used to craft tranquilizers.',
    'rarity': '1',
    'value': '5',
    'maxCapacity': '10',
}, {
    'name': 'Slicing Ammo',
    'icon': require('./assets/items/ammo_white.png'),
    'description': 'Ammo that ejects sharp blades on impact, which can sever tails. Capacity: 30',
    'rarity': '2',
    'value': '3',
    'maxCapacity': '30',
}, {
    'name': 'Small Barrel',
    'icon': require('./assets/items/barrel_bright_yellow.png'),
    'description': 'A small, empty barrel.',
    'rarity': '1',
    'value': '8',
    'maxCapacity': '10',
}, {
    'name': 'Smokenut',
    'icon': require('./assets/items/herb_white.png'),
    'description': 'A nut that produces a copious amount of smoke. Combine with other items to create smoke with various properties.',
    'rarity': '1',
    'value': '4',
    'maxCapacity': '10',
}, {
    'name': 'Snow Herb',
    'icon': require('./assets/items/herb_white.png'),
    'description': 'A plant that radiates ice-cold air. Use in combinations to create freeze ammo.',
    'rarity': '2',
    'value': '6',
    'maxCapacity': '20',
}, {
    'name': 'Spider Web',
    'icon': require('./assets/items/web_white.png'),
    'description': 'A very sticky web. Used to craft pitfall traps.',
    'rarity': '1',
    'value': '6',
    'maxCapacity': '10',
}, {
    'name': 'Spread Ammo 1',
    'icon': require('./assets/items/ammo_green.png'),
    'description': 'Ammo that covers a wide area. Deals multiple hits at close range. Capacity: 80',
    'rarity': '1',
    'value': '1',
    'maxCapacity': '80',
}, {
    'name': 'Spread Ammo 2',
    'icon': require('./assets/items/ammo_green.png'),
    'description': 'High-grade ammo that covers a wide area. Deals more hits than Spread Ammo 1. Capacity: 70',
    'rarity': '2',
    'value': '2',
    'maxCapacity': '70',
}, {
    'name': 'Spring Blossom Ticket',
    'icon': require('./assets/items/paper_pink.png'),
    'description': 'A ticket you receive for attending the Spring Blossom Fest. Can be exchanged for special equipment or fireworks.',
    'rarity': '4',
    'value': '200',
    'maxCapacity': '99',
}, {
    'name': 'Star Fireworks',
    'icon': require('./assets/items/bomb_white.png'),
    'description': 'Fireworks you receive for attending the Winter Star Fest. Enjoy the festivities with a bang!',
    'rarity': '3',
    'value': '7',
    'maxCapacity': '10',
},{
    'name': 'Steel Egg',
    'icon': require('./assets/items/egg_white.png'),
    'description': 'An egg of glilttering steel. Valuable and rare, but of no use to a hunter. (Trade-in Item)',
    'rarity': '4',
    'value': '1000',
    'maxCapacity': '99',
}, {
    'name': 'Steel Wyverian Print',
    'icon': require('./assets/items/paper_yellow.png'),
    'description': 'A ticket with a handprint, used by the First Wyverians. Exchange it for materials at the Melding Pot.',
    'rarity': '4',
    'value': '0',
    'maxCapacity': '99',
}, {
    'name': 'Sticky Ammo 1',
    'icon': require('./assets/items/ammo_orange.png'),
    'description': 'Powerful ammo that lodges in a target and explodes. Also stuns. Capacity: 9',
    'rarity': '1',
    'value': '2',
    'maxCapacity': '9',
}, {
    'name': 'Sticky Ammo 2',
    'icon': require('./assets/items/ammo_orange.png'),
    'description': 'Very powerful ammo that lodges in a target and explodes. Also stuns. Capacity: 9',
    'rarity': '2',
    'value': '3',
    'maxCapacity': '9',
}, {
    'name': 'Streamstone',
    'icon': require('./assets/items/unknown_purple.png'),
    'description': 'A rare stone taken froma tempered monster. A crystal of pure power, born of a beast\'s endless desires.',
    'rarity': '7',
    'value': '2000',
    'maxCapacity': '99',
}, {
    'name': 'Streamstone Shard',
    'icon': require('./assets/items/unknown_purple.png'),
    'description': 'A rare stone taken from a tempered monster. The longer a beast\'s reign of terror the larger the shard.',
    'rarity': '6',
    'value': '1000',
    'maxCapacity': '99',
}, {
    'name': 'Thunderbug',
    'icon': require('./assets/items/bug_bright_yellow.png'),
    'description': 'An insect that emits electricity when struck. Required to craft Shock Traps and Thunder Ammo.',
    'rarity': '4',
    'value': '80',
    'maxCapacity': '10',
}, {
    'name': 'Thunder Ammo',
    'icon': require('./assets/items/ammo_yellow.png'),
    'description': 'Ammo that packs a punch against monsters susceptible to thunder. Capacity: 60',
    'rarity': '2',
    'value': '2',
    'maxCapacity': '60',
}, {
    'name': 'Toadstool',
    'icon': require('./assets/items/mushroom_purple.png'),
    'description': 'A poisonous fungus. Can be used as a toxin for knives.',
    'rarity': '2',
    'value': '8',
    'maxCapacity': '10',
}, {
    'name': 'Tranq Ammo',
    'icon': require('./assets/items/ammo_red.png'),
    'description': 'Bowgun ammo used to capture monsters ensnared in traps. Capacity: 8',
    'rarity': '3',
    'value': '4',
    'maxCapacity': '8',
}, {
    'name': 'Tranq Bomb',
    'icon': require('./assets/items/smoke_red.png'),
    'description': 'A hand grenade used to capture monsters ensared in traps. Can be slammed against the ground.',
    'rarity': '3',
    'value': '35',
    'maxCapacity': '8',
}, {
    'name': 'Trap Tool',
    'icon': require('./assets/items/trap_tool.png'),
    'description': 'A must-have item for putting together pitfall traps and other kinds of traps.',
    'rarity': '3',
    'value': '20',
    'maxCapacity': '2',
}, {
    'name': 'Twilight Fireworks',
    'icon': require('./assets/items/bomb_blue.png'),
    'description': 'Fireworks you receive for attending the Summer Twilight Fest. Enjoy the summer heat with a bang!',
    'rarity': '3',
    'value': '7',
    'maxCapacity': '10',
}, {
    'name': 'Val Habar Quartz',
    'icon': require('./assets/items/ore_white.png'),
    'description': 'An Old World import. Beautiful, but not suitable for crafting. (Trade-in Item)',
    'rarity': '6',
    'value': '2000',
    'maxCapacity': '99',
}, {
    'name': 'Voucher',
    'icon': require('./assets/items/paper_white.png'),
    'description': 'Redeem this for a special meal with stronger effects than usual.',
    'rarity': '4',
    'value': '500',
    'maxCapacity': '99',
}, {
    'name': 'Warrior\'s Streamstone: Axe',
    'icon': require('./assets/monster_materials/warrior-streamstone.jpg'),
    'description': 'A material used by champions of old. Used to bring out the hidden power in switch axes and charge blades.',
    'rarity': '6',
    'value': '10000',
    'maxCapacity': '10',
}, {
    'name': 'Warrior\'s Streamstone: Blade',
    'icon': require('./assets/monster_materials/warrior-streamstone.jpg'),
    'description': 'A material used by champions of old. Used to bring out the hidden power in swords and shields and dual blades.',
    'rarity': '6',
    'value': '10000',
    'maxCapacity': '10',
}, {
    'name': 'Warrior\'s Streamstone: Lance',
    'icon': require('./assets/monster_materials/warrior-streamstone.jpg'),
    'description': 'A material used by champions of old. Used to bring out the hidden power in lances and gunlances.',
    'rarity': '6',
    'value': '10000',
    'maxCapacity': '10',
}, {
    'name': 'Warrior\'s Streamstone: Ranged',
    'icon': require('./assets/monster_materials/warrior-streamstone.jpg'),
    'description': 'A material used by champions of old. Used to bring out the hidden power in light bowguns and heavy bowguns.',
    'rarity': '6',
    'value': '10000',
    'maxCapacity': '10',
}, {
    'name': 'Water Ammo',
    'icon': require('./assets/items/ammo_blue.png'),
    'description': 'Ammo that packs a punch against monsters susceptible to water. Capacity: 60',
    'rarity': '2',
    'value': '2',
    'maxCapacity': '60',
}, {
    'name': 'Well-done Steak',
    'icon': require('./assets/items/meat_orange.png'),
    'description': 'Provides a moderate boost to your stamina and keeps it max for a longer period. Meat done right!',
    'rarity': '2',
    'value': '48',
    'maxCapacity': '10',
}, {
    'name': 'Wyvern Ammo',
    'icon': require('./assets/items/ammo_yellow.png'),
    'description': 'Ammo created through years of research into Wyvern\'s Fire. Capacity: 5',
    'rarity': '3',
    'value': '6',
    'maxCapacity': '5',
}, ];

export { items }